version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ngx01
    ports:
      - "8000:8000"
    volumes:
      - ./supervisord_overseer:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./collected_statics:/static
    depends_on:
      - web

  web:
    build: .
    image: overseer:1
    container_name: overseer01
    command: bash -c "python manage.py makemigrations --settings=supervisord_overseer.settings.docker && python manage.py migrate --settings=supervisord_overseer.settings.docker && python manage.py collectstatic --noinput --settings=supervisord_overseer.settings.docker && gunicorn supervisord_overseer.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./supervisord_overseer:/src
      - /etc/supervisord_overseer/db:/db
      - ./collected_statics:/static
    expose:
      - "8000"